"""C2PA Content Credentials. A manifest is positive provenance; absence proves nothing
(Midjourney and most phones don't sign), so a missing manifest is "not applicable".
"""
from __future__ import annotations

import io
import json

from ...contracts import Signal

NAME = "c2pa"
MIME = {"JPEG": "image/jpeg", "PNG": "image/png", "HEIF": "image/heic",
        "WEBP": "image/webp", "TIFF": "image/tiff"}
BROKEN = ("mismatch", "invalid", "missing")   # validation codes that mean tampering
                                              # ("untrusted" = unknown signer, not tampering)


def read_manifest(data: bytes, mime: str) -> dict | None:
    """Manifest store as a dict, or None when the file carries no manifest."""
    import c2pa  # c2pa-python; API varies by version — see docs/ISSUES.txt

    try:
        reader = c2pa.Reader(mime, io.BytesIO(data))
    except Exception as e:
        if "notfound" in f"{type(e).__name__}{e}".lower().replace(" ", ""):
            return None
        raise
    try:
        return json.loads(reader.json())
    finally:
        getattr(reader, "close", lambda: None)()


def run(prep) -> Signal:
    mime = MIME.get(prep.fmt)
    store = read_manifest(prep.data, mime) if mime else None
    if not store:
        return Signal(NAME, None, 0.0, "Not applicable: no Content Credentials in this file "
                      "(most cameras and Midjourney don't sign, so this proves nothing).",
                      applicable=False)

    m = store["manifests"][store["active_manifest"]]
    gen = m.get("claim_generator") or ", ".join(
        i.get("name", "") for i in m.get("claim_generator_info", [])) or "unknown software"
    actions = [a for asr in m.get("assertions", []) if asr.get("label", "").startswith("c2pa.actions")
               for a in asr.get("data", {}).get("actions", [])]
    sources = [str(a.get("digitalSourceType", "")).rsplit("/", 1)[-1] for a in actions]
    names = sorted({str(a.get("action", "")).removeprefix("c2pa.") for a in actions} - {""})
    broken = [v.get("code", "") for v in store.get("validation_status", [])
              if any(b in v.get("code", "").lower() for b in BROKEN)]
    ev = {"claim_generator": gen, "actions": names, "sources": sources, "broken": broken,
          "issuer": m.get("signature_info", {}).get("issuer")}

    if broken:
        return Signal(NAME, 0.7, 0.5, f"Content Credentials present but they do not verify "
                      f"({broken[0]}) — the file changed after signing.", ev)
    if "trainedAlgorithmicMedia" in sources:
        return Signal(NAME, 0.97, 0.95, f"Content Credentials: generated by AI ({gen}).", ev)
    if "compositeWithTrainedAlgorithmicMedia" in sources:
        return Signal(NAME, 0.9, 0.9, f"Content Credentials: edited with generative AI ({gen}).", ev)
    if set(names) - {"created", "opened", "placed"}:
        return Signal(NAME, 0.6, 0.6, f"Content Credentials signed by {gen}; recorded edits: "
                      f"{', '.join(names)}.", ev)
    return Signal(NAME, 0.05, 0.9, f"Content Credentials: signed capture by {gen}, no edits.", ev)
